### ISSUE TITLE
got following message on npm install

### ISSUE THREAD

**Issue by prodev42** [jawerty/Node2Blog#3]
npm ERR! install Couldn't read dependencies
npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: /root/blog/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Linux 3.8.0-19-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "."
npm ERR! cwd /root/blog
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! file /root/blog/package.json
npm ERR! code EJSONPARSE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/blog/npm-debug.log
npm ERR! not ok code 0

**Comment by jawerty** [comment]
The package.json wasn't in proper format. Add a curly bracket to the end of the file or re-clone the repo and try again, it should work.
