### ISSUE TITLE
weird characters shown during installation on clean ubuntu vm

### ISSUE THREAD

**Issue by prodev42** [jawerty/Node2Blog#4]
make: Entering directory `/root/blog/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory`/root/blog/node_modules/mongodb/node_modules/bson/build'
jade@0.28.2 node_modules/jade
â”œâ”€â”€ commander@0.6.1
â””â”€â”€ mkdirp@0.3.5

rss@0.0.4 node_modules/rss
â””â”€â”€ xml@0.0.7

mongoose@3.6.5 node_modules/mongoose
â”œâ”€â”€ sliced@0.0.3
â”œâ”€â”€ muri@0.3.1
â”œâ”€â”€ hooks@0.2.1
â”œâ”€â”€ mpath@0.1.1
â”œâ”€â”€ ms@0.1.0
â””â”€â”€ mpromise@0.2.1 (sliced@0.0.4)

express@3.0.0-rc5 node_modules/express
â”œâ”€â”€ methods@0.0.1
â”œâ”€â”€ fresh@0.1.0
â”œâ”€â”€ range-parser@0.0.4
â”œâ”€â”€ cookie@0.0.4
â”œâ”€â”€ crc@0.2.0
â”œâ”€â”€ debug@0.7.2
â”œâ”€â”€ commander@0.6.1
â”œâ”€â”€ mkdirp@0.3.3
â”œâ”€â”€ send@0.1.0 (mime@1.2.6)
â””â”€â”€ connect@2.5.0 (pause@0.0.1, bytes@0.1.0, send@0.0.4, formidable@1.0.11, qs@0.5.1)

mongodb@1.2.14 node_modules/mongodb
â””â”€â”€ bson@0.1.8

**Comment by jawerty** [comment]
Is this making it not install and run properly?

**Comment by prodev42** [comment]
my blog seems to be running okay on port 3000

**Comment by jawerty** [comment]
I don't know what the symbols mean but if the blog's dependencies are being installed properly then I wouldn't worry about it. Might be an issue with npm or even your vm. It's probably a not a Node2Blog problem either way since the package.json isn't anything special.

**Comment by prodev42** [comment]
could you add some option to make importing screenshots more easily? i think programmers like to show alot of screenshot and currently there are not enough good way to get screenshots into the blogs easily(via browser addon or drop it into directory for the blog system to recognize)..also a way to paste code using markdown or gist.github.com integration or something...

**Comment by jawerty** [comment]
I do like the markdown idea, but you can already import images to the blog post, it's just in the editor toolbar. The markdown editor is a really good idea though, it would be cool if there was an option to write in either markdown of the normal editor.

**Comment by prodev42** [comment]
yah but i have to first write down a name for my picture...then find a location to store the pics...and then type down the pic's name manually and the location's url...which is alot of work...especially if i take alot of screenshot to show ppl something...im thinking more like windows live writer where you can just alt-v a screenshot u just capture without even saving..into your editor and it will directly upload into the blog system..

**Comment by jawerty** [comment]
You can drag images to the canvas as well. I'm not sure how convenient you'd like it to be. What do you suggest?

**Comment by prodev42** [comment]
either you drop the files into a directory and the blog pick it up based on how it's named....
like ->    http://smallvictori.es/
or something like microsoft live writer where I can just take a screen shot and paste it into the blog without even have to save to jpg..
if the canvas already let me do the above then ignore my request =)

update: i just tried ...the canvas didnt let me paste the pic i just cutted via pic capturing tool

**Comment by jawerty** [comment]
You can already drag images from your local file system. I don't know if it's worth making the screenshot shortcut since it's a little much for something that I don't even believe is that much better than dragging files from your folders to the canvas. However, you could certainly implement that if you'd like, would be an interesting js project IMO :).

**Comment by prodev42** [comment]
alright then...whats the best way to show  codes on the blog currently....

**Comment by jawerty** [comment]
Sadly the best options now are to use the code tag or edit them manually. That is however a big issue I'm working through.

**Comment by prodev42** [comment]
k keep up the good work..
